

# Figures


```{r, fig.cap = 'Results', echo=FALSE, fig.width=8, fig.height=8}
# if(values.imported()) {
# cos <- get("costs", envir=session)
# eff <- get("effects", envir=session)
# 
#  make.4way.plot(costs.int = cos, effects.int = eff, incremental.int = input$incremental,
#                  ceac.int = ceac.obj, lambda.int=input$lambda2, main1=input$main, xlab1=input$xlab, 
#                  ylab1=input$ylab, col1=2, main2=input$main, xlab2=input$xlab, 
#                  ylab2=input$ylab, col2=3)
# }
```



```{r, fig.cap = 'Cost-effectiveness plane', echo=FALSE, fig.width=4, fig.height=4}
# if(values.imported()) {
#   plot(inc_effects, inc_costs,  main=paste("lambda =", input$lambda), cex.main=0.8, xlab=input$xlab, 
#   ylab=input$ylab, col=1, pty="s",
#   ylim=c(-m3.costs, m3.costs), xlim=c(-m3.effects, m3.effects))
#   abline(1, input$lambda2, lty=2, col=3)
#   abline(h=0)
#   abline(v=0)
# }
```


```{r, fig.cap = 'CEAC', echo=FALSE, fig.width=4, fig.height=4}
# if(values.imported()) {
#   make.CEACplot(ceac.obj, lambda=input$lambda2, main=input$main2, xlab=input$xlab2, ylab=input$ylab2,
#                   col=3)
#   abline(v=0)
# }
```

```{r, fig.cap = 'EVPI (on health scale) with respect to lambda', echo=FALSE, fig.width=4, fig.height=4}
# if(values.imported()) {
#   cos <- get("costs", envir=cacheEnv)
#   eff <- get("effects", envir=cacheEnv)
#   make.EVPIplot(costs.int = cos, effects.int = eff, incremental.int = input$incremental, 
#                    costscale = FALSE, main="test.main", xlab="testx", ylab="testy",
#                    col=2)
# }
```
